namespace ArchIntel.GraphStore.Contracts.Enums;

public enum NodeType
{
    Solution,
    Project,
    Assembly,
    Namespace,
    Class,
    Interface,
    Record,
    Struct,
    Enum,
    Method,
    Constructor,
    Property,
    Field,
    Controller,
    MinimalApiEndpoint,
    MediatRHandler,
    DomainEvent,
    IntegrationEvent,
    EfEntity,
    EfDbContext,
    Repository,
    Service,
    BackgroundWorker,
    HostedService,
    MessageQueue,
    ExternalSystem,
    ConfigurationSection,
    TestClass,
    TestMethod,
}
