using System.CommandLine;
using System.Text;
using Arch.Cli.Output;
using ArchScanner.Core.Workspace;
using Spectre.Console;

namespace Arch.Cli.Commands;

/// <summary>`arch init` — scaffolds arch.yml (03-cli.md Section 4, "arch init").</summary>
public static class InitCommand
{
    public static Command Build()
    {
        var pathOption = new Option<string?>("--path") { Description = "Target directory (default: cwd)" };
        var solutionOption = new Option<string?>("--solution") { Description = "Explicit .sln path; if omitted, globs for a single *.sln" };
        var forceOption = new Option<bool>("--force") { Description = "Overwrite an existing arch.yml" };
        var minimalOption = new Option<bool>("--minimal") { Description = "Emit a bare-bones config without inline comments" };

        var command = new Command("init", "Scaffold a new arch.yml, auto-detecting the solution file if possible.")
        {
            pathOption, solutionOption, forceOption, minimalOption,
        };

        command.SetAction(parseResult => RunAsync(
            parseResult.GetValue(pathOption) ?? parseResult.GetValue(GlobalOptions.Cwd)!,
            parseResult.GetValue(solutionOption),
            parseResult.GetValue(forceOption),
            parseResult.GetValue(minimalOption),
            OutputWriterFactory.Create(parseResult)));

        return command;
    }

    public static Task<int> RunAsync(string path, string? explicitSolution, bool force, bool minimal, IOutputWriter output)
    {
        var targetDir = Path.GetFullPath(path);
        Directory.CreateDirectory(targetDir);

        var configPath = Path.Combine(targetDir, "arch.yml");
        if (File.Exists(configPath) && !force)
        {
            output.WriteError($"{configPath} already exists. Re-run with --force to overwrite.");
            return Task.FromResult(ExitCodes.UserError);
        }

        string solutionPath;
        if (explicitSolution is not null)
        {
            solutionPath = Path.GetFullPath(explicitSolution, targetDir);
            if (!File.Exists(solutionPath))
            {
                output.WriteError($"Solution file not found: {solutionPath}");
                return Task.FromResult(ExitCodes.UserError);
            }
        }
        else
        {
            var candidates = Directory.GetFiles(targetDir, "*.sln", SearchOption.TopDirectoryOnly);
            var isInteractive = !Console.IsInputRedirected && !Console.IsOutputRedirected;

            if (candidates.Length == 0)
            {
                output.WriteError("No .sln file found. Pass --solution <path> to specify one explicitly.");
                return Task.FromResult(ExitCodes.UserError);
            }

            if (candidates.Length == 1)
            {
                solutionPath = candidates[0];
            }
            else if (isInteractive)
            {
                var chosenName = AnsiConsole.Prompt(
                    new SelectionPrompt<string>()
                        .Title("Multiple solution files found. Select one:")
                        .AddChoices(candidates.Select(c => Path.GetFileName(c)!)));
                solutionPath = candidates.First(c => Path.GetFileName(c) == chosenName);
            }
            else
            {
                output.WriteError("Multiple .sln files found and input is not interactive. Pass --solution <path> to disambiguate.");
                return Task.FromResult(ExitCodes.UserError);
            }
        }

        var structure = SolutionStructureReader.Read(solutionPath);
        var orderedProjectNames = SolutionStructureReader.DeriveScanOrder(structure);
        var scanOrder = SolutionStructureReader.ShortenToLayerLabels(orderedProjectNames);

        var relativeSolution = Path.GetRelativePath(targetDir, solutionPath).Replace('\\', '/');
        var yaml = minimal
            ? BuildMinimalYaml(relativeSolution, scanOrder)
            : BuildCommentedYaml(relativeSolution, scanOrder);

        File.WriteAllText(configPath, yaml);

        output.WriteRaw($"Detected {structure.Projects.Count} projects: {string.Join(", ", scanOrder)}");
        output.WriteRaw($"Wrote {configPath}");
        output.WriteRaw(string.Empty);
        output.WriteRaw("Next steps:");
        output.WriteRaw("  arch scan     # build the architecture graph");
        output.WriteRaw("  arch doctor   # verify your environment is ready");

        return Task.FromResult(ExitCodes.Success);
    }

    private static string BuildCommentedYaml(string solution, IReadOnlyList<string> scanOrder)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# arch.yml — Architecture Intelligence Platform configuration");
        sb.AppendLine("# Generated by `arch init`");
        sb.AppendLine();
        sb.AppendLine("# Path to the .NET solution to scan (relative to this file).");
        sb.AppendLine($"solution: {solution}");
        sb.AppendLine();
        sb.AppendLine("# Projects are scanned in this order — dependencies before dependents.");
        sb.AppendLine("# Auto-derived from project references; reorder if your architecture needs it.");
        sb.AppendLine("scanOrder:");
        foreach (var project in scanOrder)
        {
            sb.AppendLine($"  - {project}");
        }

        sb.AppendLine();
        sb.AppendLine("# Directories to skip during scanning.");
        sb.AppendLine("ignore:");
        sb.AppendLine("  - bin");
        sb.AppendLine("  - obj");
        sb.AppendLine("  - node_modules");
        sb.AppendLine();
        sb.AppendLine("# Languages this scan covers (currently only 'csharp' is supported).");
        sb.AppendLine("languages:");
        sb.AppendLine("  - csharp");
        sb.AppendLine();
        sb.AppendLine("# Which relationship types the scanner should follow.");
        sb.AppendLine("rules:");
        sb.AppendLine("  followInheritance: true");
        sb.AppendLine("  followDI: true");
        sb.AppendLine("  followMediatR: true");
        sb.AppendLine("  followProjectReferences: true");
        sb.AppendLine();
        sb.AppendLine("# Where the resulting architecture graph is stored.");
        sb.AppendLine("storage:");
        sb.AppendLine("  provider: sqlite");
        sb.AppendLine("  connectionString: .arch/graph.db");

        return sb.ToString();
    }

    private static string BuildMinimalYaml(string solution, IReadOnlyList<string> scanOrder)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"solution: {solution}");
        sb.AppendLine("scanOrder:");
        foreach (var project in scanOrder)
        {
            sb.AppendLine($"  - {project}");
        }

        sb.AppendLine("ignore: [bin, obj, node_modules]");
        sb.AppendLine("languages: [csharp]");
        sb.AppendLine("rules: { followInheritance: true, followDI: true, followMediatR: true, followProjectReferences: true }");
        sb.AppendLine("storage: { provider: sqlite, connectionString: .arch/graph.db }");

        return sb.ToString();
    }
}
